#!/bin/sh
MUSL_VER=1.1.22
BUSYBOX_VER=1.30.1
SUDO_VER=1.8.27

BASE=/root
MUSL_PREFIX=$BASE/musl
ROOTFS=/rootfs
KHDR_BASE=/usr
PATH=$MUSL_PREFIX/bin:$PATH

# extract source
cd $BASE
tar xf /mac/src/musl-1.1.22.tar.gz
tar xf /mac/src/busybox-1.30.1.tar.bz2

# build musl c library
cd $BASE/musl-$MUSL_VER
./configure --prefix=$MUSL_PREFIX --disable-shared 1>/dev/null
make -j8 install 1>/dev/null 2>&1

# use binutils and linux-headers from the buildhost
ln -s `which ar` $MUSL_PREFIX/bin/musl-ar
ln -s `which strip` $MUSL_PREFIX/bin/musl-strip
ln -s $KHDR_BASE/include/linux $MUSL_PREFIX/include/linux
ln -s $KHDR_BASE/include/mtd $MUSL_PREFIX/include/mtd
if [ -d $KHDR_BASE/include/asm ]; then
  ln -s $KHDR_BASE/include/asm $MUSL_PREFIX/include/asm
else
  ln -s $KHDR_BASE/include/asm-generic $MUSL_PREFIX/include/asm
fi
ln -s $KHDR_BASE/include/asm-generic $MUSL_PREFIX/include/asm-generic

# build busybox
cd $BASE/busybox-$BUSYBOX_VER
make defconfig 1>/dev/null
sed -i -e "s/.*CONFIG_CROSS_COMPILER_PREFIX=.*/CONFIG_CROSS_COMPILER_PREFIX=\"musl-\"/" \
       -e "s|.*CONFIG_PREFIX=.*|CONFIG_PREFIX=\"$ROOTFS\"|" \
       -e "s/.*CONFIG_STATIC=.*/CONFIG_STATIC=y/" \
       -e "s/.*CONFIG_PIE=.*/\# CONFIG_PIE is not set/" \
       .config
make V=1 -j8 1>/dev/null 2>&1
echo Installing busybox
make install

# package rootfs
cd $ROOTFS
tar czf /mac/busybox.tar.gz .
