#!/bin/sh
ver=`cat /mac/KERNEL_VERSION`
exclude_modules=true

umount /mnt 2> /dev/null

dd if=/dev/zero of=/system.part bs=512 count=7500 2>/dev/null \
  && mkfs.ext4 /system.part 1>/dev/null \
  && mount /system.part /mnt \
  && {
    cd /mnt \
      && rmdir lost+found \
      && tar xf /mac/busybox.tar.gz \
      && cp -r /mac/system/* . \
      && find . -name .gitkeep -delete
      && ($exclude_modules || cp -a /mac/kernel-stuff/$ver/modules lib/) \
      && cd / \
      && umount /mnt \
      && mv /system.part /mac/ \
      && echo 'system partition created successfully.'
  }
