#!/bin/sh
ver=`cat /mac/KERNEL_VERSION`

umount /mnt 2> /dev/null

dd if=/dev/zero of=/system.part bs=1M count=32 \
  && mkfs.ext4 -L SYSTEM /system.part 1>/dev/null \
  && mount /system.part /mnt \
  && {
    cd /mnt \
      && tar xf /mac/busybox.tar.gz \
      && cp -r /mac/system/* . \
      && cd / \
      && umount /mnt \
      && mv /system.part /mac/ \
      && echo 'system partition created successfully.'
  }
