#!/bin/sh
ver=`cat /mac/KERNEL_VERSION`

dd if=/dev/zero of=/boot.part bs=1M count=48 \
  && mkfs.fat -F32 /boot.part 1>/dev/null \
  && mount /boot.part /mnt \
  && {
    cd /mnt \
      && cp -a /uefi/EFI . \
      && cp /mac/kernel-stuff/$ver/vmlinuz . \
      && cp /mac/initrd.gz . \
      && cp /mac/grub.cfg EFI/BOOT/ \
      && cd / \
      && umount /mnt \
      && mv /boot.part /mac/ \
      && echo 'boot partition created successfully.'
  }
