#!/bin/sh
ver=`cat /mac/KERNEL_VERSION`

losetup -D
dd if=/dev/zero of=/boot.disk bs=1M count=48 1>/dev/null \
  && parted -s /boot.disk mktable gpt \
  && parted -s /boot.disk mkpart fat32 34s 98270s 1>/dev/null 2>&1 \
  && losetup -f /boot.disk \
  && {
    partx -d --nr 1 /dev/loop0
    partx -a --sector-size 512 /dev/loop0 &&
      mkfs.fat -F32 /dev/loop0p1 1>/dev/null \
        && mount /dev/loop0p1 /mnt \
        && {
          cd /mnt \
            && cp -a /uefi/EFI . \
            && cp /mac/kernel-stuff/$ver/vmlinuz . \
            && cp /mac/initrd.gz . \
            && cp /mac/grub.cfg EFI/BOOT/ \
            && cd / \
            && umount /mnt \
            && succeed=true
        }

      losetup -d /dev/loop0 \
        && $succeed \
        && mv /boot.disk /mac/ \
        && echo 'boot disk created successfully.'
  }
