#!/bin/sh

ROOTFS=/rootfs

rm -rf $ROOTFS

./configure --prefix=$ROOTFS/usr \
            --libexecdir=$ROOTFS/usr/lib \
            --with-secure-path \
            --with-all-insults \
            --enable-static-sudoers 1>/dev/null

make -j8 1>/dev/null
make install 1>/dev/null
